apiVersion: apps/v1
kind: Deployment
metadata:
  name: notes-md-ui
  labels:
    app: notes-md-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notes-md-ui
  template:
    metadata:
      labels:
        app: notes-md-ui
    spec:
      containers:
        - name: notes-md-ui
          image: uherman/notes-md-ui:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: PUBLIC_API_URL
              value: ${PUBLIC_API_URL}
---
apiVersion: v1
kind: Service
metadata:
  name: notes-md-ui
spec:
  type: NodePort
  selector:
    app: notes-md-ui
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: notes-md-ui
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    ingressClassName: traefik
spec:
  tls:
    - hosts:
        - notes.null.care
        - www.notes.null.care
      secretName: notes-md-tls
  rules:
    - host: notes.null.care
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: notes-md-ui
                port:
                  number: 3000
    - host: www.notes.null.care
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: notes-md-ui
                port:
                  number: 3000
