apiVersion: apps/v1
kind: Deployment
metadata:
  name: notes-md-ui
  labels:
    app: notes-md-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notes-md-ui
  template:
    metadata:
      labels:
        app: notes-md-ui
    spec:
      containers:
        - name: notes-md-ui
          image: uherman/notes-md-ui:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: PUBLIC_API_URL
              value: ${PUBLIC_API_URL}
---
apiVersion: v1
kind: Service
metadata:
  name: notes-md-ui
spec:
  type: NodePort
  selector:
    app: notes-md-ui
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
