apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: notes-md-api
  name: notes-md-api
spec:
  selector:
    matchLabels:
      app: notes-md-api
  replicas: 1
  template:
    metadata:
      labels:
        app: notes-md-api
        name: notes-md-api
    spec:
      containers:
        - name: notes-md-api
          image: "uherman/notes-md-api:latest"
          imagePullPolicy: Always
          resources:
            requests:
              memory: "256Mi"
            limits:
              memory: "256Mi"
          ports:
            - containerPort: 8000
          env:
            - name: REDIS_URL
              value: ${REDIS_URL}
            - name: RUST_LOG
              value: info
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: notes-md-api
  name: notes-md-api
spec:
  selector:
    app: notes-md-api
  ports:
    - port: 8000
      name: http
      protocol: TCP
  type: ClusterIP
